#!/bin/sh -e

export DESTDIR="$1"

# Don't fail on building xcursor.c
# See https://github.com/swaywm/wlroots/issues/2777
export CFLAGS="$CFLAGS -Wno-error"

meson \
    --prefix=/usr \
    -Dexamples=false \
    -Dxwayland=enabled \
    -Dx11-backend=enabled \
    -Dxdg-foreign=enabled \
    . output

ninja -C output
ninja -C output install
