#!/bin/sh -e

sed -i 's|fcft/fcft.h|fcft.h|g' meson.build
sed -i 's|fcft/stride.h|stride.h|g' meson.build

sed -i 's|fcft/fcft.h|fcft.h|g' fcft.c
sed -i 's|fcft/stride.h|stride.h|g' fcft.c

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    . output

ninja -C output
ninja -C output install
