#!/bin/sh -e

# Script used to build gammastep in an alpine chroot.
# Build artifacts can be found in the ./gammastep-v$ver/output/ folder.

# Set g_ver to the version of gammastep you're trying to build
ver=2.0.2

# Install required dependencies
apk add alpine-sdk autoconf automake gettext-dev intltool libtool wayland-dev

# Build flags
export CFLAGS='-march=x86-64 -mtune=generic -pipe -Os'
export CXXFLAGS='-march=x86-64 -mtune=generic -pipe -Os'
export LDFLAGS='-static'
export MAKEFLAGS='-j12' # Make sure to adjust to your number of threads

wget "https://gitlab.com/chinstrap/gammastep/-/archive/v$ver/gammastep-v$ver.tar.gz"
tar vxf "gammastep-v$ver.tar.gz" && cd "gammastep-v$ver"

./bootstrap
./configure --prefix="$PWD/output"

make
make install
