#!/bin/sh

cat <<EOF

NOTE: Install the 'hicolor-icon-theme' package if
      no other icon themes are installed.

NOTE: Launch firefox with the '--no-remote' flag
      to avoid firefox segfaulting.

EOF
