#!/bin/sh

cat <<EOF

NOTE: Launch with 'MOZ_ENABLE_WAYLAND=1' to run
      with the wayland backend.

NOTE: Install the 'hicolor-icon-theme' package if
      no other icon themes are installed.

NOTE: Install the 'firefox-privacy' package to
      enable extra privacy restrictions.

NOTE: This includes more telemetry removals,
      hardened settings, no phoning-home etc.

EOF
